
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      # - ES_JAVA_OPTS="-Xmx1g -Xms1g"  # 根據需要調整內存大小，目前為 1g，Xmx使用的最大內存，Xms初始內存
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data  # 儲存 Elasticsearch 數據，此為 linux 列的路徑
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.0.0
    container_name: logstash
    # environment:
      # - LS_JAVA_OPTS="-Xmx1g -Xms1g"  # 調整 Logstash 內存
    ports:
      - "5044:5044"  # 用於 Filebeat 或其他工具的輸入端口
      - "9600:9600"  # Logstash 監控端口
    volumes:
      - logstash_logs:/usr/share/logstash/data  # 儲存處理過的日誌
      # - logstash.conf:/usr/share/logstash/config/logstash.conf  # Logstash 配置文件
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # 指向 Elasticsearch
    ports:
      - "5601:5601"  # Kibana 用於瀏覽日誌和查詢的端口
    networks:
      - elk

volumes:
  elasticsearch_data:  # 用於 Elasticsearch 數據的 Volume
  logstash_logs:  # 用於 Logstash 日誌數據的 Volume
    external: false  # 如果需要外部掛載，可以設定為 true，讓它在容器外部保存

networks:
  elk:
    driver: bridge
