
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      # - ES_JAVA_OPTS="-Xmx1g -Xms1g"  # 根據需要調整內存大小，目前為 1g，Xmx使用的最大內存，Xms初始內存
    ports:
      - "9200:9200"
    volumes:
      - ~/project/elasticsearch_data:/usr/share/elasticsearch/data  # 映射到 ~/project/elasticsearch_data
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.0.0
    container_name: logstash
    # environment:
      # - LS_JAVA_OPTS="-Xmx1g -Xms1g"  # 調整 Logstash 內存
    ports:
      - "5044:5044"  # 用於 Filebeat 或其他工具的輸入端口
      - "9600:9600"  # Logstash 監控端口
    volumes:
      - ~/project/logstash_logs:/usr/share/logstash/data  # 映射到 ~/project/logstash_logs
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # 指向 Elasticsearch
    ports:
      - "5601:5601"  # Kibana 用於瀏覽日誌和查詢的端口
    networks:
      - elk

networks:
  elk:
    driver: bridge
